/**
 * Demo cohort data for Cohort Analyzer demonstration
 * Contains 3 pre-configured cohorts with interesting biological/clinical comparisons
 */

export const demoCohorts = [
  {
    cohortId: "demo-ganglioglioma-surgery",
    cohortName: "Demo Cohort 1: Ganglioglioma Surgery",
    cohortDescription: "Participants with Ganglioglioma NOS who underwent surgical treatment - demonstrating low-grade tumor characteristics and treatment outcomes",
    participants: [
      { participant_id: "PBBHTY", dbgap_accession: "phs002790", participant_pk: "demo_PBBHTY" },
      { participant_id: "PBBPGL", dbgap_accession: "phs002790", participant_pk: "demo_PBBPGL" },
      { participant_id: "PBBLLB", dbgap_accession: "phs002790", participant_pk: "demo_PBBLLB" },
      { participant_id: "PBBMYK", dbgap_accession: "phs002790", participant_pk: "demo_PBBMYK" },
      { participant_id: "PBBNSG", dbgap_accession: "phs002790", participant_pk: "demo_PBBNSG" },
      { participant_id: "PBBNXT", dbgap_accession: "phs002790", participant_pk: "demo_PBBNXT" },
      { participant_id: "PBBKXM", dbgap_accession: "phs002790", participant_pk: "demo_PBBKXM" },
      { participant_id: "PBBPME", dbgap_accession: "phs002790", participant_pk: "demo_PBBPME" },
      { participant_id: "PBBWJX", dbgap_accession: "phs002790", participant_pk: "demo_PBBWJX" },
      { participant_id: "PBBUKV", dbgap_accession: "phs002790", participant_pk: "demo_PBBUKV" },
      { participant_id: "PBBNFF", dbgap_accession: "phs002790", participant_pk: "demo_PBBNFF" },
      { participant_id: "PBBNHL", dbgap_accession: "phs002790", participant_pk: "demo_PBBNHL" },
      { participant_id: "PBBSTM", dbgap_accession: "phs002790", participant_pk: "demo_PBBSTM" },
      { participant_id: "PBBPWE", dbgap_accession: "phs002790", participant_pk: "demo_PBBPWE" },
      { participant_id: "PBBSTE", dbgap_accession: "phs002790", participant_pk: "demo_PBBSTE" },
      { participant_id: "PBBRIL", dbgap_accession: "phs002790", participant_pk: "demo_PBBRIL" },
      { participant_id: "PBBRJF", dbgap_accession: "phs002790", participant_pk: "demo_PBBRJF" },
      { participant_id: "PBBJGY", dbgap_accession: "phs002790", participant_pk: "demo_PBBJGY" },
      { participant_id: "PBBNFS", dbgap_accession: "phs002790", participant_pk: "demo_PBBNFS" },
      { participant_id: "PBBPPY", dbgap_accession: "phs002790", participant_pk: "demo_PBBPPY" },
      { participant_id: "PBBNGE", dbgap_accession: "phs002790", participant_pk: "demo_PBBNGE" },
      { participant_id: "PBBSZR", dbgap_accession: "phs002790", participant_pk: "demo_PBBSZR" },
      { participant_id: "PBBUXY", dbgap_accession: "phs002790", participant_pk: "demo_PBBUXY" },
      { participant_id: "PBBIJB", dbgap_accession: "phs002790", participant_pk: "demo_PBBIJB" },
      { participant_id: "PBBRXN", dbgap_accession: "phs002790", participant_pk: "demo_PBBRXN" }
    ],
    lastUpdated: new Date().toISOString(),
  },
  {
    cohortId: "demo-malignant-chemo-immuno",
    cohortName: "Demo Cohort 2: Malignant Glioma Chemo/Immuno",
    cohortDescription: "Participants with malignant Glioma treated with chemotherapy and immunotherapy - representing aggressive treatment approaches for high-grade tumors",
    participants: [
      { participant_id: "PBBJHS", dbgap_accession: "phs002790", participant_pk: "demo_PBBJHS_1" },
      { participant_id: "PBBKKT", dbgap_accession: "phs002790", participant_pk: "demo_PBBKKT" },
      { participant_id: "PBBIUS", dbgap_accession: "phs002790", participant_pk: "demo_PBBIUS_1" },
      { participant_id: "PBBLPZ", dbgap_accession: "phs002790", participant_pk: "demo_PBBLPZ" },
      { participant_id: "PBBIUN", dbgap_accession: "phs002790", participant_pk: "demo_PBBIUN_1" },
      { participant_id: "PBBHYH", dbgap_accession: "phs002790", participant_pk: "demo_PBBHYH" },
      { participant_id: "PBBMCU", dbgap_accession: "phs002790", participant_pk: "demo_PBBMCU" },
      { participant_id: "PBBKNA", dbgap_accession: "phs002790", participant_pk: "demo_PBBKNA" },
      { participant_id: "PBBKTU", dbgap_accession: "phs002790", participant_pk: "demo_PBBKTU" },
      { participant_id: "PBBMZW", dbgap_accession: "phs002790", participant_pk: "demo_PBBMZW_1" },
      { participant_id: "PBBIIW", dbgap_accession: "phs002790", participant_pk: "demo_PBBIIW" },
      { participant_id: "PBBMCC", dbgap_accession: "phs002790", participant_pk: "demo_PBBMCC" },
      { participant_id: "PBBIGN", dbgap_accession: "phs002790", participant_pk: "demo_PBBIGN" },
      { participant_id: "PBBKKX", dbgap_accession: "phs002790", participant_pk: "demo_PBBKKX_1" },
      { participant_id: "PBBMCL", dbgap_accession: "phs002790", participant_pk: "demo_PBBMCL" },
      { participant_id: "PBBMNW", dbgap_accession: "phs002790", participant_pk: "demo_PBBMNW" },
      { participant_id: "PBBIXN", dbgap_accession: "phs002790", participant_pk: "demo_PBBIXN" },
      { participant_id: "PBBMBK", dbgap_accession: "phs002790", participant_pk: "demo_PBBMBK" },
      { participant_id: "PBBHWP", dbgap_accession: "phs002790", participant_pk: "demo_PBBHWP_1" },
      { participant_id: "PBBLWR", dbgap_accession: "phs002790", participant_pk: "demo_PBBLWR" },
      { participant_id: "PBBKSG", dbgap_accession: "phs002790", participant_pk: "demo_PBBKSG_1" },
      { participant_id: "PBBMYD", dbgap_accession: "phs002790", participant_pk: "demo_PBBMYD_1" },
      { participant_id: "PBBLFW", dbgap_accession: "phs002790", participant_pk: "demo_PBBLFW_1" },
      { participant_id: "PBBMYI", dbgap_accession: "phs002790", participant_pk: "demo_PBBMYI" },
      { participant_id: "PBBIXR", dbgap_accession: "phs002790", participant_pk: "demo_PBBIXR" }
    ],
    lastUpdated: new Date().toISOString(),
  },
  {
    cohortId: "demo-malignant-glioma-radiation",
    cohortName: "Demo Cohort 3: Malignant Glioma Radiation",
    cohortDescription: "Participants with malignant Glioma treated with radiation therapy - showcasing radiation-based treatment protocols for brain tumors",
    participants: [
      { participant_id: "PBBNIZ", dbgap_accession: "phs002790", participant_pk: "demo_PBBNIZ" },
      { participant_id: "PBBJHS", dbgap_accession: "phs002790", participant_pk: "demo_PBBJHS_2" },
      { participant_id: "PBBVDX", dbgap_accession: "phs002790", participant_pk: "demo_PBBVDX" },
      { participant_id: "PBBVPC", dbgap_accession: "phs002790", participant_pk: "demo_PBBVPC" },
      { participant_id: "PBBIUS", dbgap_accession: "phs002790", participant_pk: "demo_PBBIUS_2" },
      { participant_id: "PBBIUN", dbgap_accession: "phs002790", participant_pk: "demo_PBBIUN_2" },
      { participant_id: "PBBVZJ", dbgap_accession: "phs002790", participant_pk: "demo_PBBVZJ" },
      { participant_id: "PBBMZW", dbgap_accession: "phs002790", participant_pk: "demo_PBBMZW_2" },
      { participant_id: "PBBTRI", dbgap_accession: "phs002790", participant_pk: "demo_PBBTRI" },
      { participant_id: "PBBVUD", dbgap_accession: "phs002790", participant_pk: "demo_PBBVUD" },
      { participant_id: "PBBNCU", dbgap_accession: "phs002790", participant_pk: "demo_PBBNCU" },
      { participant_id: "PBBSIU", dbgap_accession: "phs002790", participant_pk: "demo_PBBSIU" },
      { participant_id: "PBBRKP", dbgap_accession: "phs002790", participant_pk: "demo_PBBRKP" },
      { participant_id: "PBBMJP", dbgap_accession: "phs002790", participant_pk: "demo_PBBMJP" },
      { participant_id: "PBBUNA", dbgap_accession: "phs002790", participant_pk: "demo_PBBUNA" },
      { participant_id: "PBBKKX", dbgap_accession: "phs002790", participant_pk: "demo_PBBKKX_2" },
      { participant_id: "PBBHWP", dbgap_accession: "phs002790", participant_pk: "demo_PBBHWP_2" },
      { participant_id: "PBBLHT", dbgap_accession: "phs002790", participant_pk: "demo_PBBLHT" },
      { participant_id: "PBBRKJ", dbgap_accession: "phs002790", participant_pk: "demo_PBBRKJ" },
      { participant_id: "PBBTCS", dbgap_accession: "phs002790", participant_pk: "demo_PBBTCS" },
      { participant_id: "PBBKSG", dbgap_accession: "phs002790", participant_pk: "demo_PBBKSG_2" },
      { participant_id: "PBBMYD", dbgap_accession: "phs002790", participant_pk: "demo_PBBMYD_2" },
      { participant_id: "PBBLFW", dbgap_accession: "phs002790", participant_pk: "demo_PBBLFW_2" },
      { participant_id: "PBBSKM", dbgap_accession: "phs002790", participant_pk: "demo_PBBSKM" },
      { participant_id: "PBBTED", dbgap_accession: "phs002790", participant_pk: "demo_PBBTED" }
    ],
    lastUpdated: new Date().toISOString(),
  }
];

